--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ShockedPlot7560/FactionMaster-Bank
build-by-default: true
branches:
- master
projects:
  FactionMaster-Bank:
    path: ""
    libs:
    - src: jojoe77777/FormAPI/libFormAPI
      version: ^1.3
...
