name: FactionMasterBank
author: ShockedPlot7560
version: 1.4.1
api: 3.17.7
main: ShockedPlot7560\FactionMasterBank\FactionMasterBank
depend: [EconomyAPI, FactionMaster]
softdepend: ["ScoreHud"]
description: "Extension which implements a bank system"
