name: FactionMasterBank
author: ShockedPlot7560
version: 1.1.0
api: 3.17.7
main: ShockedPlot7560\FactionMasterBank\FactionMasterBank
depend: [EconomyAPI, FactionMaster]
virions: ["libFormAPI"]
description: "Extension which implements a bank system"
